
package com.gemalto.latamsoft.oi.brasil.callcenter.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RecuperarCompraAvulsaWsImplService", targetNamespace = "http://ws.callcenter.brasil.oi.latamsoft.gemalto.com/", wsdlLocation = "http://localhost:8081/oi-brasil-callcenter-soap-ws/services/RecuperarCompraAvulsaWs?wsdl")
public class RecuperarCompraAvulsaWsImplService
    extends Service
{

    private final static URL RECUPERARCOMPRAAVULSAWSIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.gemalto.latamsoft.oi.brasil.callcenter.client.RecuperarCompraAvulsaWsImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.gemalto.latamsoft.oi.brasil.callcenter.client.RecuperarCompraAvulsaWsImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/oi-brasil-callcenter-soap-ws/services/RecuperarCompraAvulsaWs?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/oi-brasil-callcenter-soap-ws/services/RecuperarCompraAvulsaWs?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RECUPERARCOMPRAAVULSAWSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public RecuperarCompraAvulsaWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecuperarCompraAvulsaWsImplService() {
        super(RECUPERARCOMPRAAVULSAWSIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.callcenter.brasil.oi.latamsoft.gemalto.com/", "RecuperarCompraAvulsaWsImplService"));
    }

    /**
     * 
     * @return
     *     returns RecuperarCompraAvulsaWs
     */
    @WebEndpoint(name = "RecuperarCompraAvulsaWsImplPort")
    public RecuperarCompraAvulsaWs getRecuperarCompraAvulsaWsImplPort() {
        return super.getPort(new QName("http://ws.callcenter.brasil.oi.latamsoft.gemalto.com/", "RecuperarCompraAvulsaWsImplPort"), RecuperarCompraAvulsaWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecuperarCompraAvulsaWs
     */
    @WebEndpoint(name = "RecuperarCompraAvulsaWsImplPort")
    public RecuperarCompraAvulsaWs getRecuperarCompraAvulsaWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.callcenter.brasil.oi.latamsoft.gemalto.com/", "RecuperarCompraAvulsaWsImplPort"), RecuperarCompraAvulsaWs.class, features);
    }

}
