
package com.gemalto.latamsoft.oi.brasil.callcenter.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RecuperarCompraAvulsaWs", targetNamespace = "http://ws.callcenter.brasil.oi.latamsoft.gemalto.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecuperarCompraAvulsaWs {


    /**
     * 
     * @param recuperarCompraAvulsaRequest
     * @return
     *     returns com.gemalto.latamsoft.oi.brasil.callcenter.client.RecuperarCompraAvulsaResponseType
     */
    @WebMethod(operationName = "RecuperarCompraAvulsa")
    @WebResult(name = "RecuperarCompraAvulsaResponse", targetNamespace = "")
    @RequestWrapper(localName = "RecuperarCompraAvulsa", targetNamespace = "http://ws.callcenter.brasil.oi.latamsoft.gemalto.com/", className = "com.gemalto.latamsoft.oi.brasil.callcenter.client.RecuperarCompraAvulsa")
    @ResponseWrapper(localName = "RecuperarCompraAvulsaResponse", targetNamespace = "http://ws.callcenter.brasil.oi.latamsoft.gemalto.com/", className = "com.gemalto.latamsoft.oi.brasil.callcenter.client.RecuperarCompraAvulsaResponse")
    public RecuperarCompraAvulsaResponseType recuperarCompraAvulsa(
        @WebParam(name = "RecuperarCompraAvulsaRequest", targetNamespace = "")
        RecuperarCompraAvulsaRequestType recuperarCompraAvulsaRequest);

}
