
package com.gemalto.latamsoft.oi.brasil.callcenter.cxf.client3;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Jun 05 15:56:27 ART 2013
 * Generated source version: 2.2.9
 * 
 */

public final class RecuperarCompraAvulsaWs_RecuperarCompraAvulsa_Client {

    private static final QName SERVICE_NAME = new QName("http://alsb.telemar/xsd", "RecuperarCompraAvulsaWs");

    private RecuperarCompraAvulsaWs_RecuperarCompraAvulsa_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = RecuperarCompraAvulsaWs_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RecuperarCompraAvulsaWs_Service ss = new RecuperarCompraAvulsaWs_Service(wsdlURL, SERVICE_NAME);
        RecuperarCompraAvulsaWs port = ss.getRecuperarCompraAvulsa();  
        
        {
        	 System.out.println("Invoking recuperarCompraAvulsa...");
             com.gemalto.latamsoft.oi.brasil.callcenter.cxf.client3.RecuperarCompraAvulsa b = new com.gemalto.latamsoft.oi.brasil.callcenter.cxf.client3.RecuperarCompraAvulsa();
             com.gemalto.latamsoft.oi.brasil.callcenter.cxf.client3.RecuperarCompraAvulsaRequestType a = new com.gemalto.latamsoft.oi.brasil.callcenter.cxf.client3.RecuperarCompraAvulsaRequestType();
             a.setUsuario("user");
             a.setSenha("0ibr4s1l");
             a.setTransacao("121212");
             a.setMsisdn("123456789012");
             b.setRecuperarCompraAvulsaRequest(a);
             com.gemalto.latamsoft.oi.brasil.callcenter.cxf.client3.RecuperarCompraAvulsaResponse _recuperarCompraAvulsa__return = port.recuperarCompraAvulsa(b);
             System.out.println("recuperarCompraAvulsa.result=" + _recuperarCompraAvulsa__return);

        }

        System.exit(0);
    }

}
