
package spring.ejemplos.diecisiete.ws.cxf.client.jaxwsgeneratedcode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWS", targetNamespace = "http://ws.cxf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "decirHola", targetNamespace = "http://ws.cxf.com/", className = "spring.ejemplos.diecisiete.ws.cxf.client.jaxwsgeneratedcode.DecirHola")
    @ResponseWrapper(localName = "decirHolaResponse", targetNamespace = "http://ws.cxf.com/", className = "spring.ejemplos.diecisiete.ws.cxf.client.jaxwsgeneratedcode.DecirHolaResponse")
    public String decirHola(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param legajo
     * @return
     *     returns spring.ejemplos.diecisiete.ws.cxf.client.jaxwsgeneratedcode.Persona
     */
    @WebMethod
    @WebResult(name = "persona", targetNamespace = "")
    @RequestWrapper(localName = "buscarPersona", targetNamespace = "http://ws.cxf.com/", className = "spring.ejemplos.diecisiete.ws.cxf.client.jaxwsgeneratedcode.BuscarPersona")
    @ResponseWrapper(localName = "buscarPersonaResponse", targetNamespace = "http://ws.cxf.com/", className = "spring.ejemplos.diecisiete.ws.cxf.client.jaxwsgeneratedcode.BuscarPersonaResponse")
    public Persona buscarPersona(
        @WebParam(name = "legajo", targetNamespace = "")
        long legajo);

}
