
package com.gemalto.latamsoft.oi.brasil.callcenter.cxf.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Jun 03 19:57:16 ART 2013
 * Generated source version: 2.2.3
 * 
 */

public final class RecuperarCompraAvulsaWs_RecuperarCompraAvulsaWsImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.callcenter.brasil.oi.latamsoft.gemalto.com/", "RecuperarCompraAvulsaWsImplService");

    private RecuperarCompraAvulsaWs_RecuperarCompraAvulsaWsImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = RecuperarCompraAvulsaWsImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RecuperarCompraAvulsaWsImplService ss = new RecuperarCompraAvulsaWsImplService(wsdlURL, SERVICE_NAME);
        RecuperarCompraAvulsaWs port = ss.getRecuperarCompraAvulsaWsImplPort();  
      
        // To override the URL endpoint..
     	BindingProvider bp = (BindingProvider)port;
        bp.getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, "http://localhost:8081/oi-brasil-callcenter-soap-ws/services/RecuperarCompraAvulsaWs");

        {
        System.out.println("Invoking recuperarCompraAvulsa...");
        com.gemalto.latamsoft.oi.brasil.callcenter.cxf.client.RecuperarCompraAvulsaRequestType _recuperarCompraAvulsa_recuperarCompraAvulsaRequest = null;
        com.gemalto.latamsoft.oi.brasil.callcenter.cxf.client.RecuperarCompraAvulsaResponseType _recuperarCompraAvulsa__return = port.recuperarCompraAvulsa(new com.gemalto.latamsoft.oi.brasil.callcenter.cxf.client.RecuperarCompraAvulsaRequestType());
        System.out.println("recuperarCompraAvulsa.result=" + _recuperarCompraAvulsa__return);


        }

        System.exit(0);
    }

}
