
/*
 * 
 */

package com.gemalto.latamsoft.oi.brasil.callcenter.cxf.client2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Wed Jun 05 15:03:00 ART 2013
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "RecuperarCompraAvulsaWsImplService", 
                  wsdlLocation = "http://localhost:8081/oi-brasil-callcenter-soap-ws/services/RecuperarCompraAvulsaWs?wsdl",
                  targetNamespace = "http://xsd.alsb.telemar/") 
public class RecuperarCompraAvulsaWsImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://xsd.alsb.telemar/", "RecuperarCompraAvulsaWsImplService");
    public final static QName RecuperarCompraAvulsaWsImplPort = new QName("http://xsd.alsb.telemar/", "RecuperarCompraAvulsaWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/oi-brasil-callcenter-soap-ws/services/RecuperarCompraAvulsaWs?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8081/oi-brasil-callcenter-soap-ws/services/RecuperarCompraAvulsaWs?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public RecuperarCompraAvulsaWsImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RecuperarCompraAvulsaWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecuperarCompraAvulsaWsImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns RecuperarCompraAvulsaWs
     */
    @WebEndpoint(name = "RecuperarCompraAvulsaWsImplPort")
    public RecuperarCompraAvulsaWs getRecuperarCompraAvulsaWsImplPort() {
        return super.getPort(RecuperarCompraAvulsaWsImplPort, RecuperarCompraAvulsaWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecuperarCompraAvulsaWs
     */
    @WebEndpoint(name = "RecuperarCompraAvulsaWsImplPort")
    public RecuperarCompraAvulsaWs getRecuperarCompraAvulsaWsImplPort(WebServiceFeature... features) {
        return super.getPort(RecuperarCompraAvulsaWsImplPort, RecuperarCompraAvulsaWs.class, features);
    }

}
