
package com.gemalto.latamsoft.vtr.chile.ws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "VTRApiSOAPException", targetNamespace = "http://ws.chile.vtr.latamsoft.gemalto.com/")
public class VTRApiSOAPException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private VTRApiSOAPException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public VTRApiSOAPException_Exception(String message, VTRApiSOAPException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public VTRApiSOAPException_Exception(String message, VTRApiSOAPException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.gemalto.latamsoft.vtr.chile.ws.client.VTRApiSOAPException
     */
    public VTRApiSOAPException getFaultInfo() {
        return faultInfo;
    }

}
