
package com.gemalto.latamsoft.vtr.chile.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "VtrSucursalVirtualWSImplService", targetNamespace = "http://ws.chile.vtr.latamsoft.gemalto.com/", wsdlLocation = "http://localhost:8081/vtr_chile/services/VtrSucursalVirtualWS?wsdl")
public class VtrSucursalVirtualWSImplService
    extends Service
{

    private final static URL VTRSUCURSALVIRTUALWSIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.gemalto.latamsoft.vtr.chile.ws.client.VtrSucursalVirtualWSImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.gemalto.latamsoft.vtr.chile.ws.client.VtrSucursalVirtualWSImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/vtr_chile/services/VtrSucursalVirtualWS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/vtr_chile/services/VtrSucursalVirtualWS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VTRSUCURSALVIRTUALWSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public VtrSucursalVirtualWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VtrSucursalVirtualWSImplService() {
        super(VTRSUCURSALVIRTUALWSIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.chile.vtr.latamsoft.gemalto.com/", "VtrSucursalVirtualWSImplService"));
    }

    /**
     * 
     * @return
     *     returns VtrSucursalVirtualWS
     */
    @WebEndpoint(name = "VtrSucursalVirtualWSImplPort")
    public VtrSucursalVirtualWS getVtrSucursalVirtualWSImplPort() {
        return super.getPort(new QName("http://ws.chile.vtr.latamsoft.gemalto.com/", "VtrSucursalVirtualWSImplPort"), VtrSucursalVirtualWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VtrSucursalVirtualWS
     */
    @WebEndpoint(name = "VtrSucursalVirtualWSImplPort")
    public VtrSucursalVirtualWS getVtrSucursalVirtualWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.chile.vtr.latamsoft.gemalto.com/", "VtrSucursalVirtualWSImplPort"), VtrSucursalVirtualWS.class, features);
    }

}
