
package com.gemalto.latamsoft.vtr.chile.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "VtrSucursalVirtualWS", targetNamespace = "http://ws.chile.vtr.latamsoft.gemalto.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VtrSucursalVirtualWS {


    /**
     * 
     * @param msisdn
     * @throws VTRApiSOAPException
     */
    @WebMethod
    @RequestWrapper(localName = "sendAllSettings", targetNamespace = "http://ws.chile.vtr.latamsoft.gemalto.com/", className = "com.gemalto.latamsoft.vtr.chile.ws.client.SendAllSettings")
    @ResponseWrapper(localName = "sendAllSettingsResponse", targetNamespace = "http://ws.chile.vtr.latamsoft.gemalto.com/", className = "com.gemalto.latamsoft.vtr.chile.ws.client.SendAllSettingsResponse")
    public void sendAllSettings(
        @WebParam(name = "msisdn", targetNamespace = "")
        String msisdn)
        throws VTRApiSOAPException
    ;

    /**
     * 
     * @param msisdn
     * @param serviceName
     * @throws VTRApiSOAPException
     */
    @WebMethod
    @RequestWrapper(localName = "sendSetting", targetNamespace = "http://ws.chile.vtr.latamsoft.gemalto.com/", className = "com.gemalto.latamsoft.vtr.chile.ws.client.SendSetting")
    @ResponseWrapper(localName = "sendSettingResponse", targetNamespace = "http://ws.chile.vtr.latamsoft.gemalto.com/", className = "com.gemalto.latamsoft.vtr.chile.ws.client.SendSettingResponse")
    public void sendSetting(
        @WebParam(name = "msisdn", targetNamespace = "")
        String msisdn,
        @WebParam(name = "serviceName", targetNamespace = "")
        String serviceName)
        throws VTRApiSOAPException
    ;

    /**
     * 
     * @param msisdn
     * @return
     *     returns com.gemalto.latamsoft.vtr.chile.ws.client.Terminal
     * @throws VTRApiSOAPException
     */
    @WebMethod
    @WebResult(name = "terminal", targetNamespace = "")
    @RequestWrapper(localName = "getModelByMSISDN", targetNamespace = "http://ws.chile.vtr.latamsoft.gemalto.com/", className = "com.gemalto.latamsoft.vtr.chile.ws.client.GetModelByMSISDN")
    @ResponseWrapper(localName = "getModelByMSISDNResponse", targetNamespace = "http://ws.chile.vtr.latamsoft.gemalto.com/", className = "com.gemalto.latamsoft.vtr.chile.ws.client.GetModelByMSISDNResponse")
    public Terminal getModelByMSISDN(
        @WebParam(name = "msisdn", targetNamespace = "")
        String msisdn)
        throws VTRApiSOAPException
    ;

}
