
package com.gemalto.latamsoft.nuevatel.bolivia.cem.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DMServiceImplService", targetNamespace = "http://ws.cem.dmmodules.nuevatel.bolivia.latamtelcosoft.gemalto.com/", wsdlLocation = "http://localhost:8081/cem-ws-1.0.0-ALPHA01/DMService?wsdl")
public class DMServiceImplService
    extends Service
{

    private final static URL DMSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.gemalto.latamsoft.nuevatel.bolivia.cem.ws.client.DMServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.gemalto.latamsoft.nuevatel.bolivia.cem.ws.client.DMServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/cem-ws-1.0.0-ALPHA01/DMService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/cem-ws-1.0.0-ALPHA01/DMService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DMSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public DMServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DMServiceImplService() {
        super(DMSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.cem.dmmodules.nuevatel.bolivia.latamtelcosoft.gemalto.com/", "DMServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns DMService
     */
    @WebEndpoint(name = "DMServiceImplPort")
    public DMService getDMServiceImplPort() {
        return super.getPort(new QName("http://ws.cem.dmmodules.nuevatel.bolivia.latamtelcosoft.gemalto.com/", "DMServiceImplPort"), DMService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DMService
     */
    @WebEndpoint(name = "DMServiceImplPort")
    public DMService getDMServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.cem.dmmodules.nuevatel.bolivia.latamtelcosoft.gemalto.com/", "DMServiceImplPort"), DMService.class, features);
    }

}
