
package com.gemalto.latamsoft.nuevatel.bolivia.cem.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DMService", targetNamespace = "http://ws.cem.dmmodules.nuevatel.bolivia.latamtelcosoft.gemalto.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DMService {


    /**
     * 
     * @param msisdn
     * @return
     *     returns com.gemalto.latamsoft.nuevatel.bolivia.cem.ws.client.Capabilities
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Capabilities getCapabilities(
        @WebParam(name = "msisdn", partName = "msisdn")
        String msisdn)
        throws ServiceException_Exception
    ;

}
