
/*
 * 
 */

package spring.ejemplos.diecisiete.ws.cxf.client.cxfgeneratedcode;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Oct 19 13:58:10 ART 2012
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "HelloWSImplService", 
                  wsdlLocation = "http://localhost:8080/SpringCXFProject/HelloWS?wsdl",
                  targetNamespace = "http://ws.cxf.com/") 
public class HelloWSImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.cxf.com/", "HelloWSImplService");
    public final static QName HelloWSImplPort = new QName("http://ws.cxf.com/", "HelloWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SpringCXFProject/HelloWS?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/SpringCXFProject/HelloWS?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public HelloWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns HelloWS
     */
    @WebEndpoint(name = "HelloWSImplPort")
    public HelloWS getHelloWSImplPort() {
        return super.getPort(HelloWSImplPort, HelloWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWS
     */
    @WebEndpoint(name = "HelloWSImplPort")
    public HelloWS getHelloWSImplPort(WebServiceFeature... features) {
        return super.getPort(HelloWSImplPort, HelloWS.class, features);
    }

}
